[package]
name = "kurtex"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
deno_ast = { version = "0.38.2", features = ["transpiling"] }
deno_core = "0.283.0"
reqwest = "0.12.5"
tokio = { version = "1.38.1", features = ["full"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
globwalk = "0.9.1"
regex = "1.10.5"
globmatch = "0.3.0"

[build-dependencies]
deno_core = "0.283.0"

[[bin]]
name = "kurtex"
