[package]
name = "kurtex"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
deno_ast = { version = "0.38.2", features = ["transpiling"] }
deno_core = "0.283.0"
reqwest = "0.12.4"
tokio = { version = "1.28.0", features = ["full"] }
serde = { version = "1.0.203", features = ["derive"] }

[build-dependencies]
deno_core = "0.283.0"

[[bin]]
name = "kurtex"