name: Unit tests

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/unit-tests.yml'
      - 'src/**'
      - 'Cargo.*'
      - build.rs
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/unit-tests.yml'
      - 'src/**'
      - 'Cargo.*'
      - 'kurtex_cli/build.rs'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

env:
  RUSTFLAGS: --deny warnings

jobs:
  unit-tests:
    name: unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Act dependencies
        if: ${{ env.ACT }}
        run: |
          apt-get update && apt-get install sudo -y

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install curl build-essential -y

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2

      - uses: extractions/setup-just@v2
        env:
          just-version: '1.4.0'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run rustfmt and clippy checks
        run: just lint

      - name: Run tests
        run: just test
