name: Unit tests

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/unit-tests.yml'
      - 'src/**'
      - 'Cargo.*'
      - build.rs
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/unit-tests.yml'
      - 'src/**'
      - 'Cargo.*'
      - 'crates/kurtex_cli/build.rs'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

env:
  RUSTFLAGS: --deny warnings

jobs:
  unit-tests:
    name: unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Act dependencies
        if: ${{ env.ACT }}
        run: |
          apt-get update && apt-get install sudo -y

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install curl build-essential -y

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2

      - name: Install valgrind
        shell: bash
        run: |
          # Installing packages
          sudo rm /var/lib/man-db/auto-update || true
          sudo apt-get update && sudo apt-get install -y --no-install-recommends valgrind
      - name: Cargo test (valgrind)
        shell: bash
        run: |
          CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUNNER="
            valgrind --error-exitcode=1 --leak-check=no
            --suppressions=/home/runner/work/deno_core/deno_core/.github/workflows/ci-test-valgrind/suppressions.txt
            --gen-suppressions=all" \
            cargo test --workspace -- --quit 
